// Generated by Apple Swift version 6.2.3 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef MWDATDISPLAY_SWIFT_H
#define MWDATDISPLAY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import MWDATCore;
@import ObjectiveC;
#else
#import <CoreFoundation/CoreFoundation.h>
#import <MWDATCore/MWDATCore-Swift.h>
#import <objc/NSObjCRuntime.h>
#import <objc/NSObject.h>
#import <objc/message.h>
#import <objc/objc-api.h>
#import <objc/objc-auto.h>
#import <objc/objc-exception.h>
#import <objc/objc-sync.h>
#import <objc/objc.h>
#import <objc/runtime.h>
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MWDATDisplay",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@interface NSNotification (SWIFT_EXTENSION(MWDATDisplay))
/// Posted when the display capability state changes.
/// note:
/// Delivered on a background thread. Dispatch to main queue for UI updates.
/// <ul>
///   <li>
///     object: The <code>MWDATDisplay</code> instance that changed state.
///   </li>
///   <li>
///     userInfo: <code>["state": MWDATDisplayState]</code>
///   </li>
/// </ul>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull displayStateChanged;)
+ (NSNotificationName _Nonnull)displayStateChanged SWIFT_WARN_UNUSED_RESULT;
@end

/// Base class for all view components that can be displayed on glasses.
/// Subclasses include <code>ObjC_Text</code>, <code>ObjC_Button</code>, <code>ObjC_Image</code>,
/// <code>ObjC_Icon</code>, and <code>ObjC_FlexBox</code>.
SWIFT_CLASS_NAMED("ObjC_DatViewComponent")
@interface MWDATViewComponent : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
enum MWDATButtonStyle : NSInteger;
/// A button component for display on glasses.
SWIFT_CLASS_NAMED("ObjC_Button")
@interface MWDATButton : MWDATViewComponent
/// Creates a button component.
/// \param label The button label text.
///
/// \param style The button style preset. Defaults to <code>.primary</code>.
///
/// \param iconName An optional icon name string. Must match a <code>IconName</code> raw value.
///
/// \param onClick An optional tap handler block.
///
- (nonnull instancetype)initWithLabel:(NSString * _Nonnull)label style:(enum MWDATButtonStyle)style iconName:(NSString * _Nullable)iconName onClick:(void (^ _Nullable)(void))onClick OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Alignment for FlexBox children.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATAlignment, "ObjC_DatAlignment", closed) {
/// Align to the start.
  MWDATAlignmentStart = 0,
/// Align to the center.
  MWDATAlignmentCenter = 1,
/// Align to the end.
  MWDATAlignmentEnd = 2,
/// Stretch to fill.
  MWDATAlignmentStretch = 3,
};

/// Background-style options for <code>ObjC_FlexBox</code>.
/// Maps to the proto’s <code>background</code> oneof: <code>card</code> renders a WDS
/// StaticContainer-style background with rounded corners; <code>none</code> renders
/// no background.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATBackground, "ObjC_DatBackground", closed) {
/// No background.
  MWDATBackgroundNone = 0,
/// WDS card background with rounded corners.
  MWDATBackgroundCard = 1,
};

/// Button style presets.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATButtonStyle, "ObjC_DatButtonStyle", closed) {
/// Primary filled button.
  MWDATButtonStylePrimary = 0,
/// Secondary filled button.
  MWDATButtonStyleSecondary = 1,
/// Outline button.
  MWDATButtonStyleOutline = 2,
};

/// Corner radius presets for images.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATCornerRadius, "ObjC_DatCornerRadius", closed) {
/// No corner radius.
  MWDATCornerRadiusNone = 0,
/// Small corner radius.
  MWDATCornerRadiusSmall = 1,
/// Medium corner radius.
  MWDATCornerRadiusMedium = 2,
};

/// Direction for FlexBox layout.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATDirection, "ObjC_DatDirection", closed) {
/// Arrange children vertically from top to bottom.
  MWDATDirectionColumn = 0,
/// Arrange children horizontally from leading to trailing.
  MWDATDirectionRow = 1,
/// Arrange children vertically from bottom to top.
  MWDATDirectionColumnReverse = 2,
/// Arrange children horizontally from trailing to leading.
  MWDATDirectionRowReverse = 3,
};

/// A subset of edges for use with <code>ObjC_FlexBox/paddingForEdges(_:value:)</code>.
/// Mirrors the named cases of the Swift <code>Edge</code> option set. Combined edges
/// (e.g. top + leading) are not exposed here — use
/// <code>ObjC_FlexBox/paddingWithInsets(_:)</code> for arbitrary combinations.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATEdge, "ObjC_DatEdge", closed) {
/// The top edge.
  MWDATEdgeTop = 0,
/// The bottom edge.
  MWDATEdgeBottom = 1,
/// The leading (start) edge.
  MWDATEdgeLeading = 2,
/// The trailing (end) edge.
  MWDATEdgeTrailing = 3,
/// Both leading and trailing edges.
  MWDATEdgeHorizontal = 4,
/// Both top and bottom edges.
  MWDATEdgeVertical = 5,
/// All four edges.
  MWDATEdgeAll = 6,
};

/// Edge inset values for padding (in dp).
SWIFT_CLASS_NAMED("ObjC_DatEdgeInsets")
@interface MWDATEdgeInsets : NSObject
/// Top padding in dp.
@property (nonatomic, readonly) CGFloat top;
/// Bottom padding in dp.
@property (nonatomic, readonly) CGFloat bottom;
/// Leading padding in dp.
@property (nonatomic, readonly) CGFloat leading;
/// Trailing padding in dp.
@property (nonatomic, readonly) CGFloat trailing;
/// Creates edge insets with specific values for each edge.
- (nonnull instancetype)initWithTop:(CGFloat)top bottom:(CGFloat)bottom leading:(CGFloat)leading trailing:(CGFloat)trailing OBJC_DESIGNATED_INITIALIZER;
/// Creates edge insets with uniform padding on all sides.
- (nonnull instancetype)initWithAll:(CGFloat)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Icon style presets.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATIconStyle, "ObjC_DatIconStyle", closed) {
/// Filled icon.
  MWDATIconStyleFilled = 0,
/// Outline icon.
  MWDATIconStyleOutline = 1,
};

/// Image size presets.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATImageSize, "ObjC_DatImageSize", closed) {
/// 32dp icon size.
  MWDATImageSizeIcon = 0,
/// Fill parent width.
  MWDATImageSizeFill = 1,
};

/// Text color presets.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATTextColor, "ObjC_DatTextColor", closed) {
/// Primary text color.
  MWDATTextColorPrimary = 0,
/// Secondary text color.
  MWDATTextColorSecondary = 1,
};

/// Text style presets.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATTextStyle, "ObjC_DatTextStyle", closed) {
/// Large heading text.
  MWDATTextStyleHeading = 0,
/// Standard body text.
  MWDATTextStyleBody = 1,
/// Small metadata text.
  MWDATTextStyleMeta = 2,
};

@class NSError;
@class MWDATDisplay;
@interface MWDATDeviceSession (SWIFT_EXTENSION(MWDATDisplay))
/// Creates and registers a <code>MWDATDisplay</code> on this device session.
/// The session must be in <code>MWDATDeviceSessionStateStarted</code> state.
/// Call <code>MWDATDisplay/start</code> on the returned capability to begin.
/// \code
/// NSError *error = nil;
/// MWDATDisplay *display = [session addDisplayAndReturnError:&error];
/// if (error) { NSLog(@"Failed: %@", error); return; }
/// [display start];
///
/// \endcode\param outError On failure, contains the error description.
///
///
/// returns:
/// A new <code>MWDATDisplay</code> attached to this session, or <code>nil</code> on failure.
- (MWDATDisplay * _Nullable)addDisplayAndReturnError:(NSError * _Nullable * _Nullable)outError SWIFT_WARN_UNUSED_RESULT;
/// Removes the display capability from this device session.
/// Call this after stopping the display capability to allow re-attaching later.
/// \param outError On failure, contains the error description.
///
///
/// returns:
/// <code>YES</code> on success, <code>NO</code> on failure.
- (BOOL)removeDisplayAndReturnError:(NSError * _Nullable * _Nullable)outError SWIFT_WARN_UNUSED_RESULT;
@end

enum MWDATDisplayState : NSInteger;
@class MWDATFlexBox;
@class MWDATDisplayListenerToken;
@class MWDATVideoPlaybackEvent;
/// A class for managing display sessions with Meta Wearables devices.
/// Handles sending views and video content to glasses, and provides real-time state updates.
/// In addition to listener-based callbacks, this class also posts the following notification:
/// <ul>
///   <li>
///     <code>NSNotification.displayStateChanged</code> - When capability state changes
///   </li>
/// </ul>
SWIFT_CLASS_NAMED("ObjC_Display")
@interface MWDATDisplay : NSObject
/// The current state of the display capability.
@property (nonatomic, readonly) enum MWDATDisplayState state;
/// Starts the display capability session.
/// Connects to the device and prepares to send content.
/// State transitions: <code>.stopped</code> -> <code>.started</code>
- (void)start;
/// Stops the display capability session and releases all resources.
/// State transitions: <code>.started</code> -> <code>.stopped</code>
- (void)stop;
/// Sends a FlexBox view layout to the connected glasses.
/// \param view The FlexBox layout to display.
///
/// \param completion A block called when the operation completes. Passes <code>nil</code> on success,
/// or an <code>NSError</code> on failure.
///
- (void)sendView:(MWDATFlexBox * _Nonnull)view completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// Sends a video URL to the connected glasses for playback.
/// The glasses will fetch and play the video from the given URL.
/// Supported schemes are <code>http</code> and <code>https</code>.
/// \param url The video URL string.
///
/// \param completion A block called when the operation completes. Passes <code>nil</code> on success,
/// or an <code>NSError</code> on failure.
///
- (void)sendVideoWithURL:(NSString * _Nonnull)url completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// Sends a VIDEO_STOP message to the glasses to terminate any active video playback.
/// Can be called even when the iOS side is not actively streaming data — for example,
/// after all chunks have been sent but the glasses are still playing the video.
- (void)sendVideoStop;
/// Adds a listener for state changes.
/// The listener will be called whenever the capability state changes.
/// \param listener A block called with the new state value.
///
///
/// returns:
/// A token that must be retained to keep the listener active.
- (MWDATDisplayListenerToken * _Nonnull)addStateListener:(void (^ _Nonnull)(enum MWDATDisplayState))listener SWIFT_WARN_UNUSED_RESULT;
/// Called when a video playback event is received from the glasses.
@property (nonatomic, copy) void (^ _Nullable onPlaybackEvent)(MWDATVideoPlaybackEvent * _Nonnull);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Errors that can occur during display operations.
/// Since Objective-C enums cannot have associated values, the detailed error message
/// from <code>DisplayError/displayError(_:)</code> is carried by the <code>NSError</code> in completion handlers.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATDisplayError, "ObjC_DisplayError", closed) {
/// Device not found in the device manager.
  MWDATDisplayErrorDeviceNotFound = 0,
/// Device connection not available.
  MWDATDisplayErrorConnectionNotAvailable = 1,
/// Device is not connected or became disconnected during operation.
  MWDATDisplayErrorDeviceDisconnected = 2,
/// The video URL is invalid (blank or unsupported scheme).
  MWDATDisplayErrorInvalidVideoURL = 10,
/// A display error was reported by the glasses.
  MWDATDisplayErrorDisplayError = 11,
};

/// A token that can be used to cancel a listener subscription.
/// Retain this token to keep the listener active; releasing it will cancel the subscription.
SWIFT_CLASS_NAMED("ObjC_DisplayListenerToken")
@interface MWDATDisplayListenerToken : NSObject
/// Cancels the listener subscription.
- (void)cancel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents the current state of a display capability session.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATDisplayState, "ObjC_DisplayState", closed) {
/// The session is in the process of starting up.
  MWDATDisplayStateStarting = 0,
/// The session is active and ready to send content to glasses.
  MWDATDisplayStateStarted = 1,
/// The session is in the process of stopping.
  MWDATDisplayStateStopping = 2,
/// The session is completely stopped.
  MWDATDisplayStateStopped = 3,
};

/// Video codec type for video playback on glasses.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATDisplayVideoCodec, "ObjC_DisplayVideoCodec", closed) {
/// Unknown codec.
  MWDATDisplayVideoCodecUnknown = 0,
/// MP4 codec.
  MWDATDisplayVideoCodecMp4 = 1,
};

/// A flex layout container that arranges children along a configurable axis.
/// <code>ObjC_FlexBox</code> is the root-level display component. Create a <code>MWDATFlexBox</code> and pass it to
/// <code>MWDATDisplay.sendView:completion:</code> to show content on glasses.
/// \code
/// MWDATText *title = [[MWDATText alloc] initWithContent:@"Hello"
///                                                 style:MWDATTextStyleHeading
///                                                 color:MWDATTextColorPrimary];
/// MWDATFlexBox *layout = [[MWDATFlexBox alloc] initWithDirection:MWDATDirectionColumn
///                                                      children:@[title]
///                                                       spacing:12
///                                                     alignment:MWDATAlignmentCenter
///                                                crossAlignment:MWDATAlignmentStart
///                                                          wrap:NO
///                                                       padding:nil];
/// [session sendView:layout completion:^(NSError *error) {
///   if (error) { NSLog(@"Send failed: %@", error); }
/// }];
///
/// \endcode
SWIFT_CLASS_NAMED("ObjC_FlexBox")
@interface MWDATFlexBox : MWDATViewComponent
/// Creates a FlexBox layout container.
/// \param direction The layout direction. Defaults to <code>.column</code>.
///
/// \param children An array of <code>MWDATViewComponent</code> children.
///
/// \param spacing The spacing between children in dp. Defaults to <code>0</code>.
///
/// \param alignment The main axis alignment. Defaults to <code>.start</code>.
///
/// \param crossAlignment The cross axis alignment. Defaults to <code>.start</code>.
///
/// \param wrap Whether children should wrap to the next line. Defaults to <code>false</code>.
///
/// \param padding Optional padding around the container.
///
- (nonnull instancetype)initWithDirection:(enum MWDATDirection)direction children:(NSArray<MWDATViewComponent *> * _Nonnull)children spacing:(CGFloat)spacing alignment:(enum MWDATAlignment)alignment crossAlignment:(enum MWDATAlignment)crossAlignment wrap:(BOOL)wrap padding:(MWDATEdgeInsets * _Nullable)padding OBJC_DESIGNATED_INITIALIZER;
/// Sets the flex-grow factor when this FlexBox is itself a child of another FlexBox.
///
/// returns:
/// A new <code>ObjC_FlexBox</code> with the updated value.
- (MWDATFlexBox * _Nonnull)flexGrow:(float)value SWIFT_WARN_UNUSED_RESULT;
/// Sets the flex-shrink factor when this FlexBox is itself a child of another FlexBox.
///
/// returns:
/// A new <code>ObjC_FlexBox</code> with the updated value.
- (MWDATFlexBox * _Nonnull)flexShrink:(float)value SWIFT_WARN_UNUSED_RESULT;
/// Overrides the cross-axis alignment for this FlexBox when it is a child of another FlexBox.
///
/// returns:
/// A new <code>ObjC_FlexBox</code> with the updated alignment.
- (MWDATFlexBox * _Nonnull)alignSelf:(enum MWDATAlignment)value SWIFT_WARN_UNUSED_RESULT;
/// Sets uniform padding on all edges.
///
/// returns:
/// A new <code>ObjC_FlexBox</code> with the updated padding.
- (MWDATFlexBox * _Nonnull)padding:(CGFloat)value SWIFT_WARN_UNUSED_RESULT;
/// Replaces padding with the given edge insets.
///
/// returns:
/// A new <code>ObjC_FlexBox</code> with the updated padding.
- (MWDATFlexBox * _Nonnull)paddingWithInsets:(MWDATEdgeInsets * _Nonnull)insets SWIFT_WARN_UNUSED_RESULT;
/// Sets padding on a specific subset of edges.
/// \param edges The edges to apply the value to. Other edges are zeroed.
///
/// \param value The padding value in dp.
///
///
/// returns:
/// A new <code>ObjC_FlexBox</code> with the updated padding.
- (MWDATFlexBox * _Nonnull)paddingForEdges:(enum MWDATEdge)edges value:(CGFloat)value SWIFT_WARN_UNUSED_RESULT;
/// Sets the background style for this FlexBox.
///
/// returns:
/// A new <code>ObjC_FlexBox</code> with the updated background.
- (MWDATFlexBox * _Nonnull)background:(enum MWDATBackground)value SWIFT_WARN_UNUSED_RESULT;
/// Adds a tap handler invoked when this FlexBox is tapped on the wearable.
/// The renderer automatically draws an interactive background for tappable FlexBoxes.
///
/// returns:
/// A new <code>ObjC_FlexBox</code> with the tap handler set.
- (MWDATFlexBox * _Nonnull)onTap:(void (^ _Nonnull)(void))handler SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An icon component displaying a WDS icon by name on glasses.
/// Returns <code>nil</code> if the given name does not match any supported <code>IconName</code>.
SWIFT_CLASS_NAMED("ObjC_Icon")
@interface MWDATIcon : MWDATViewComponent
/// Creates an icon component.
/// \param name The WDS icon name string. Must match a <code>IconName</code> raw value.
///
/// \param style The icon style preset. Defaults to <code>.filled</code>.
///
///
/// returns:
/// <code>nil</code> if the icon name is not recognized.
- (nullable instancetype)initWithName:(NSString * _Nonnull)name style:(enum MWDATIconStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An image component loaded from a URI for display on glasses.
SWIFT_CLASS_NAMED("ObjC_Image")
@interface MWDATImage : MWDATViewComponent
/// Creates an image component.
/// \param uri The URI of the image to load.
///
/// \param sizePreset The image size preset. Defaults to <code>.icon</code>.
///
/// \param cornerRadius The corner radius preset. Defaults to <code>.none</code>.
///
- (nonnull instancetype)initWithUri:(NSString * _Nonnull)uri sizePreset:(enum MWDATImageSize)sizePreset cornerRadius:(enum MWDATCornerRadius)cornerRadius OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A text element for display on glasses.
SWIFT_CLASS_NAMED("ObjC_Text")
@interface MWDATText : MWDATViewComponent
/// Creates a text component.
/// \param content The text string to display.
///
/// \param style The text style preset. Defaults to <code>.body</code>.
///
/// \param color The text color preset. Defaults to <code>.primary</code>.
///
- (nonnull instancetype)initWithContent:(NSString * _Nonnull)content style:(enum MWDATTextStyle)style color:(enum MWDATTextColor)color OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Types of video playback errors reported by the glasses.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATVideoErrorType, "ObjC_VideoErrorType", closed) {
/// Unknown error type.
  MWDATVideoErrorTypeUnknown = 0,
/// The video URL is invalid.
  MWDATVideoErrorTypeUrlInvalid = 1,
/// A video is already playing.
  MWDATVideoErrorTypeAlreadyPlaying = 2,
/// Video playback failed.
  MWDATVideoErrorTypePlaybackFailed = 3,
};

enum MWDATVideoPlaybackEventType : NSInteger;
/// A video playback event received from the glasses.
SWIFT_CLASS_NAMED("ObjC_VideoPlaybackEvent")
@interface MWDATVideoPlaybackEvent : NSObject
/// The type of playback event.
@property (nonatomic, readonly) enum MWDATVideoPlaybackEventType type;
/// The error type, if this is an error event.
@property (nonatomic, readonly) enum MWDATVideoErrorType errorType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Types of video playback events sent from glasses to phone.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATVideoPlaybackEventType, "ObjC_VideoPlaybackEventType", closed) {
/// Unknown event type.
  MWDATVideoPlaybackEventTypeUnknown = 0,
/// Video playback has started.
  MWDATVideoPlaybackEventTypeStarted = 1,
/// Video playback has ended naturally.
  MWDATVideoPlaybackEventTypeEnded = 2,
/// Video playback was stopped by the user or system.
  MWDATVideoPlaybackEventTypeStopped = 3,
/// An error occurred during video playback.
  MWDATVideoPlaybackEventTypeError = 4,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
